<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-10-11 16:12

$extensionPath = t3lib_extMgm::extPath('ldap_sync_task');
return array(
	'tx_ldapsynctask_clitask' => $extensionPath . 'cli/class.tx_ldapsynctask_clitask.php',
	'tx_ldapsynctask_fields' => $extensionPath . 'scheduler/class.tx_ldapsynctask_fields.php',
	'tx_ldapsynctask_task' => $extensionPath . 'scheduler/class.tx_ldapsynctask_task.php',
);
?>