<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-08-04 11:02

$extensionPath = t3lib_extMgm::extPath('ldap_sync_task');
return array(
	'tx_ldapsynctask_fields' => $extensionPath . 'class.tx_ldapsynctask_fields.php',
	'tx_ldapsynctask_task' => $extensionPath . 'class.tx_ldapsynctask_task.php',
);
?>